#server:
#  port: ${PORT:8761}
#
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#  server:
#    enableSelfPreservation: false

server:
  port: ${PORT:8761}

spring:
  application:
    name: registry


eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0