#server:
#  port: ${PORT:2222}
#
#spring:
#  application:
#    name: request
#


server:
  port: 9098

spring:
  application:
    name: customer-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/