#server:
#  port: ${PORT:3333}
#
#spring:
#  application:
#    name: request
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#
#ribbon:
#  eureka:
#    enabled: true

server:
  port: ${PORT:2222}

spring:
  application:
    name: request

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/