#server:
#  port: ${PORT:2222}
#
#spring:
#  application:
#    name: gateway
#
#zuul:
#  routes:
#    request:
#      path: /request/**
#      serviceId: request
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#
#ribbon:
#  eureka:
#    enabled: true
#spring:
#  application:
#    name: gateway
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/

#ribbon:
#  eureka:
#    enabled: true

server:
port: 8765

zuul:
  routes:
    request: /request/**
    participants: /paticipants/**